# Generated by Django 4.1.6 on 2023-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_status_task_type_task_created_at_task_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
        ),
    ]
