# Generated by Django 4.1.6 on 2023-03-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_project_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='webapp.project'),
        ),
    ]
